name             "rails_app"
maintainer       "Cubolo"
maintainer_email "mkiris@cubolo.com"
license          "Apache 2.0"
description      "Creates Rails application files"
long_description IO.read(File.join(File.dirname(__FILE__), "README.md"))
version          "0.0.2"
depends          "sudo", "> 1.2.0"
depends          "hostsfile"
depends          "nginx"
depends          "monit"
depends          "rbenv"
